USEID-158 Add ADR for API keys
digitalservicebund/useid-backend-service pull request #41
Opened 2022-07-06 13:25 UTC by pgurusinga

2022-07-14 15:39 UTC, mpanne requested changes

2022-07-14 15:39 UTC, mpanne commented on doc/adr/0009-api-key.md
> +We want to filter incoming requests in the UseID backend that only client with an approved integration could access UseID endpoints.
```suggestion
We want to filter incoming requests in the UseID backend, so that only authorized clients are able to access the API.
```

2022-07-14 15:39 UTC, mpanne commented on doc/adr/0009-api-key.md
> +We use Bearer authentication. The Client (eService) should add a token in the Authorization header when requesting to the endpoints and the token should be a random string of 51 characters.
```suggestion
We use Bearer authentication. The Client (eService) should add a token in the Authorization header when requesting to the endpoints and the token should be a string of 51 characters which was issued to the client by us.
```

2022-07-14 15:39 UTC, mpanne commented on doc/adr/0009-api-key.md
> +The token should, for MVP purpose, be configured as environment variable. For the future releases, a lifecycle of token should be defined, e.g. validity of the token.
I would remove the whole sentence since it is an implementation detail which is not relevant for the decision.

2022-07-14 15:39 UTC, mpanne commented on doc/adr/0009-api-key.md
> +1. Reduce our security risk, since we only allow known client in the UseID backend
```suggestion
1. Reduce our security risk, since we only allow authorized clients to access the API
```

2022-07-14 15:39 UTC, mpanne commented on doc/adr/0009-api-key.md
> +2. Reduce resource usage, since we are filtering unknown requests, and we do not process them further
Not relevant. Would remove. I think the API key is for security reasons only.

2022-07-15 10:26 UTC, mpanne approved these changes

2022-07-15 11:14 UTC, hannesschaletzky approved these changes

2022-07-15 13:43 UTC, merged