Useid 577/universal link fallback page
digitalservicebund/useid-backend-service pull request #96
Opened 2022-10-14 14:06 UTC by hannesschaletzky

Added basic fallback page /eID-Client
Added Error Notification

Merge Conflict
`  allowed-hosts:  
     - localhost`
can be removed if necessary.

2022-10-14 14:07 UTC, hannesschaletzky commented on src/main/resources/application-local.yaml
> +    - localhost
This could be removed.

2022-10-14 15:11 UTC, mpanne requested changes

2022-10-14 15:11 UTC, mpanne commented on src/main/resources/templates/components/errorNotification.mustache
> +    <img src="https://uploads-ssl.webflow.com/617fbee004d9ae0e43297700/6347f081beb57e1344756db2_img_icon_error_filler_red.svg" loading="lazy" alt="" class="error_icon">
Please provide the image via our static directory instead of loading it from the internet. We do not control this link, so it can change which would break our view. Furthermore, loading the image via link directly to the users device makes it exploitable for delivery chain attacks.

2022-10-14 15:11 UTC, mpanne commented on src/main/resources/templates/components/errorNotification.mustache
> +        <div>Stellen Sie sicher, dass die BundesIdent App installiert ist und versuchen Sie es erneut.</div>
Since we now store all the plain text of the widget in our `application.yaml` we should be consistent and also move this text there.

2022-10-18 09:47 UTC, mpanne approved these changes

2022-10-18 09:49 UTC, merged